services:
  frontend:
    container_name: frontendcontainer
    build: .
    image: frontend:v1
    ports:
      - 80:80
    networks:
      - internalnet


networks:
  internalnet:
    driver: bridge
