services:
  mysqldb:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -P ${MYSQLDB_DOCKER_PORT} -u ${MYSQLDB_USER} -p${MYSQLDB_ROOT_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 3

    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    env_file:
      - .env

  backend:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: task-management-system
    build: .
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
         "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?serverTimezone=UTC",
         "spring.datasource.username": "${MYSQLDB_USER}", 
         "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
         "jwt.secret": "${JWT_SECRET}",
         "jwt.expiration": "${JWT_EXPIRATION}",
         "app.mail": "${APP_MAIL}",
         "spring.mail.username": "${SPRING_MAIL_USERNAME}",
         "spring.mail.password": "${SPRING_MAIL_PASSWORD}",
         "spring.security.oauth2.client.registration.google.client-id": "${OAUTH2_GOOGLE_CLIENT_ID}",
         "spring.security.oauth2.client.registration.google.client-secret": "${OAUTH2_GOOGLE_CLIENT_SECRET}",
         "dropbox.refresh.token": "${DROPBOX_REFRESH_TOKEN}",
         "dropbox.app.key": "${DROPBOX_APP_KEY}",
         "dropbox.app.secret": "${DROPBOX_APP_SECRET}"
         }'
    env_file:
      - .env
